image: python:3.6.5

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - test

before_script:
  - pip install pipenv
  - if [ ! -d "venv" ]; then virtualenv venv; fi
  - source venv/bin/activate
  - export LC_ALL=C.UTF-8; export LANG=C.UTF-8 # Pipenv/Click text encoding mitigation. See http://click.pocoo.org/5/python3/
  - pipenv install --dev

test:
  stage: test
  script:
    - nosetests tests --with-coverage
  after_script:
    - coverage xml
    - python-codacy-coverage -r coverage.xml
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  allow_failure: true
  when: always
  except:
    - schedules

pages:
  stage: build
  script:
    - cd docs_src && sphinx-apidoc -o api ../terrainlib
    - make html
    - cp -r docs/html/ public/
  artifacts:
    paths:
      - public
    name: HTML Documentation
  except:
    - schedules

build:
  stage: build
  script:
    - python setup.py sdist --formats=gztar,zip
    - mkdir TerrainLib
    - cp dist/*.{zip,gz} TerrainLib
  artifacts:
    paths:
      - TerrainLib
    name: Source distribution
  only:
    - master
    - staging
    - tags
    - schedules
