image: python:3.6.5

stages:
  - setup
  - build
  - test
  - report

dependencies:
  stage: setup
  before_script:
    - pip install pipenv
    - if [ ! -d "venv" ]; then virtualenv venv; fi
  script:
    - git diff --name-only `cat venv/last_sha || git log --oneline | tail -1 | awk '{print $1}'` | grep Pipfile; if [ "$? " = "1 " ]; then exit 0; fi
    - source venv/bin/activate
    - export LC_ALL=C.UTF-8; export LANG=C.UTF-8 # Pipenv/Click text encoding mitigation. See http://click.pocoo.org/5/python3/
    - pipenv install --dev
    - git rev-parse HEAD >> venv/last_sha
  allow_failure: true
  cache:
    paths:
      - venv
    key: "$CI_COMMIT_REF_SLUG"

build:
  stage: build
  script:
    - source venv/bin/activate
    - python setup.py sdist --formats=gztar,zip
    - mkdir TerrainLib
    - cp dist/*.{zip,gz} TerrainLib
  cache:
    paths:
      - venv
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
  artifacts:
    paths:
      - TerrainLib
    name: Source distribution
  only:
    - master
    - release/*
    - tags
    - schedules

test:
  stage: test
  script:
    - ls -alh
    - source venv/bin/activate
    - nosetests tests --with-coverage
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  cache:
    paths:
      - venv
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
  artifacts:
    paths:
      - .coverage
    when: always
  allow_failure: true
  when: always
  except:
    - schedules

pages:
  stage: report
  script:
    - ls -alh
    - source venv/bin/activate
    - sphinx-apidoc -o docs_src/api terrainlib
    - make html
    - cp -r docs/html/ public/
    - coverage html
    - cp -r htmlcov public/coverage
  allow_failure: true
  cache:
    paths:
      - venv
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
  artifacts:
    paths:
      - public
    name: HTML Documentation
  dependencies:
    - test
  except:
    - schedules

coverage:
  stage: report
  script:
    - ls -alh
    - source venv/bin/activate
    - coverage xml
    - python-codacy-coverage -r coverage.xml
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
    paths:
      - venv


