cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt-get update && apt-get install python3 python3-pip -qy
  - pip3 install pipenv
  - virtualenv venv
  - source venv/bin/activate
  - pipenv install --dev

source:
  script:
    - python setup.py sdist --formats=gztar,zip
  artifacts:
    paths:
      - dist/*
