image: python:3.6.5

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install pipenv
  - ls -alh
  - if [ ! -d "venv" ]; then virtualenv venv; fi
  - source venv/bin/activate
  - export LC_ALL=C.UTF-8; export LANG=C.UTF-8 # Pipenv/Click text encoding mitigation. See http://click.pocoo.org/5/python3/
  - pipenv install --dev

coverage-report:
  script:
    - coverage xml
    - python-codacy-coverage -r coverage.xml

test:
  script:
    - nosetests tests --with-coverage
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - .coverage
    expire_in: 15 min
  dependencies:
    - coverage-report

pages:
  script:
    - make html
  artifacts:
    paths:
      - docs/html
    name: HTML Documentation

pdf-doc:
  image: debian:latest
  before_script:
    - apt-get update -qq
    - apt-get install texlive latexmk make -yqq
  script:
    - make latex
    - cd docs/latex
    - make
  artifacts:
    paths:
      - docs/latex/*.pdf
    name: PDF Documentation

build:
  script:
    - python setup.py sdist --formats=gztar,zip
  artifacts:
    paths:
      - dist/*.zip
      - dist/*.gz
    name: Source distribution
  only:
    - master
    - staging
    - tags
