image: python:3.6.5

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - test

before_script:
  - pip install pipenv
  - ls -alh
  - if [ ! -d "venv" ]; then virtualenv venv; fi
  - source venv/bin/activate
  - export LC_ALL=C.UTF-8; export LANG=C.UTF-8 # Pipenv/Click text encoding mitigation. See http://click.pocoo.org/5/python3/
  - pipenv install --dev

test:
  stage: test
  script:
    - nosetests tests --with-coverage
  after_script:
    - coverage xml
    - python-codacy-coverage -r coverage.xml
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  allow_failure: true

pages:
  stage: build
  script:
    - make html
    - cp -r docs/html/ public/
  artifacts:
    paths:
      - public
    name: HTML Documentation

pdf-doc:
  stage: build
  image: debian:latest
  before_script:
    - apt-get update -qq
    - apt-get install texlive latexmk make -yqq
    - pipenv install --system --dev
  script:
    - make latex
    - cd docs/latex
    - make
  artifacts:
    paths:
      - docs/latex/*.pdf
    name: PDF Documentation

build:
  stage: build
  script:
    - python setup.py sdist --formats=gztar,zip
    - mkdir TerrainLib
    - cp dist/*.{zip,gz} TerrainLib
  artifacts:
    paths:
      - TerrainLib
    name: Source distribution
  only:
    - master
    - staging
    - tags
