image: python:3.6.5

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt-get update && apt-get install python3 python3-pip -qy
  - pip3 install pipenv
  - virtualenv venv
  - source venv/bin/activate
  - export LC_ALL=C.UTF-8; export LANG=C.UTF-8 # Pipenv/Click text encoding mitigation. See http://click.pocoo.org/5/python3/
  - pipenv install --dev

test:
  script:
    - nosetests tests --with-coverage
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

docs-html:
  script:
    - make html
  artifacts:
    paths:
      - docs/html/
    name: HTML Documentation

docs-latex:
  image: debian:latest
  before_script:
    - apt-get install texlive latexmk
  script:
    - make latex
    - cd docs/latex
    - make
  artifacts:
    paths:
      -docs/latex/*
    name: PDF Documentation

terrainlib:
  script:
    - python setup.py sdist --formats=gztar,zip
  artifacts:
    paths:
      - dist/*.zip
      - dist/*.gz
  only:
    - master
    - staging
    - tags
