image: python:3.6.5

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - build
  - test
  - pages

before_script:
  - pip install pipenv
  - if [ ! -d "venv" ]; then virtualenv venv; fi
  - source venv/bin/activate
  - export LC_ALL=C.UTF-8; export LANG=C.UTF-8 # Pipenv/Click text encoding mitigation. See http://click.pocoo.org/5/python3/
  - pipenv install --dev

test:
  stage: test
  script:
    - nosetests tests --with-coverage
  after_script:
    - source venv/bin/activate
    - which python
    - coverage xml
    - python-codacy-coverage -r coverage.xml
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - .coverage
    expire_in: 20 min
  allow_failure: true
  when: always
  except:
    - schedules

pages:
  stage: pages
  script:
    - ls -alh
    - sphinx-apidoc -o docs_src/api terrainlib
    - make html
    - coverage html
    - cp -r docs/html/ public/
    - cp -r htmlcov public/coverage
  artifacts:
    paths:
      - public
    name: HTML Documentation
  dependencies:
    - test
  except:
    - schedules

build:
  stage: build
  script:
    - python setup.py sdist --formats=gztar,zip
    - mkdir TerrainLib
    - cp dist/*.{zip,gz} TerrainLib
  artifacts:
    paths:
      - TerrainLib
    name: Source distribution
  only:
    - master
    - staging
    - tags
    - schedules
